# Template from https://docs.dockstore.org/en/stable/getting-started/github-apps/github-apps.html
version: 1.2
workflows:
  - name: Cellranger
    subclass: WDL
    publish: false
    primaryDescriptorPath: /workflows/cellranger/cellranger_workflow.wdl
    testParameterFiles:
      - /test/dummy.json
    authors:
      - name: Shalek Lab
        email: mgodek@broadinstitute.org
        affiliation: MIT
    filters:
      tags:
        - /.*/
      branches:
        - master